// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "underscore", "backbone", "text!templates/hello.html"], function($, _, Backbone, helloTemplate) {
  var helloView, _ref;
  return helloView = (function(_super) {
    __extends(helloView, _super);

    function helloView() {
      _ref = helloView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    helloView.prototype.el = '.js-hello';

    helloView.prototype.initialize = function() {
      var that;
      return that = this;
    };

    helloView.prototype.render = function() {
      $(this.el).html(helloTemplate);
      if ($(".js-jquery")) {
        $(".js-jquery").addClass("btn-success");
      }
      if ($(".js-backbone")) {
        return $(".js-backbone").addClass("btn-success");
      }
    };

    return helloView;

  })(Backbone.View);
});
