// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "underscore", "backbone", "views/helloView"], function($, _, Backbone, HelloView) {
  var AppRouter;
  return AppRouter = (function(_super) {
    __extends(AppRouter, _super);

    AppRouter.prototype.routes = {
      test: "testAction",
      "*actions": "defaultAction"
    };

    function AppRouter() {
      AppRouter.__super__.constructor.call(this, this.routes);
    }

    AppRouter.prototype.initialize = function() {
      this.on("route:testAction", function() {
        return $("body").append("Test");
      });
      this.on("route:defaultAction", function(actions) {
        var helloView;
        helloView = new HelloView();
        return helloView.render();
      });
      Backbone.history.start();
    };

    return AppRouter;

  })(Backbone.Router);
});
