// Generated by CoffeeScript 1.6.3
define(["jquery", "underscore", "backbone", "router"], function($, _, Backbone, Router) {
  var Application;
  return Application = (function() {
    function Application() {}

    Application.prototype.initialize = function() {
      return Router.initialize();
    };

    return Application;

  })();
});
