// Generated by CoffeeScript 1.6.3
require.config({
  paths: {
    jquery: "vendor/jquery/jquery-2.1.0-beta1",
    underscore: "vendor/underscore/underscore-min",
    backbone: "vendor/backbone/backbone-min",
    bootstrap: "vendor/bootstrap/bootstrap.min",
    text: "vendor/require/text",
    templates: "../templates"
  },
  shim: {
    bootstrap: {
      deps: ["jquery"]
    }
  }
});

require(["app", "bootstrap"], function(App, bootstrap) {
  var app;
  app = new App();
  return app.initialize();
});
